name: soctra
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dynamic_color: 1.5.4
  cached_network_image: 3.2.3
  flutter:
    sdk: flutter
  flutter_map: ^2.2.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  get_storage: ^2.0.3
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.3.1
  flutter_map_animated_marker: ^0.0.4
  firebase_storage: ^11.0.10
  intl: ^0.17.0
  image_picker: ^0.8.6
  photo_view: ^0.14.0
  material_color_utilities: ^0.1.5
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
  assets:
    - assets/images/
    - assets/sticker/
    - assets/
  uses-material-design: true
